name: Build
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "/docs"
      - "README.md"
  pull_request:
    paths-ignore:
      - "/docs"
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev libudev-dev libopenxr-loader1 libopenxr-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: "Checks"
        run: |
          cargo fmt --check --all
          #cargo clippy --no-deps --tests -- -D warnings
          #cargo rustdoc -- -D warnings
      - name: "Build"
        run: |
          cargo build
          cargo build --examples
      - name: "Test"
        run: |
          cargo test --verbose
